### ISSUE TITLE
Error running GrADSNcPlot in Centos 7

### ISSUE THREAD

**Issue by netrajit** [ictp-esp/RegCM#1]
While running GrADSNcPlot in Centos 7 system following error occurs in github release of RegCM  including RegCM4.8.1 . RegCM4.8.1 is compiled using Gfortran-4.8.5 and openmpi-3.0.1 additionally  grads-2.2.0 and NCL-6.6.2 (anaconda) are installed
[cdhmcom1@localhost REGCM_RUN]$ ./bin/GrADSNcPlot output/India-small_STS.2020060100.nc 

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7F807DBB0697
#1  0x7F807DBB0CDE
#2  0x7F807CC6A27F
#3  0x405028 in MAIN__ at GrADSNcPlot.F90:?
Segmentation fault (core dumped)

**Comment by graziano-giuliani** [comment]
Thanks, fixed on e4d6b5f

**Comment by adrfantini** [comment]
Graziano lightning fast as always ;)
