### ISSUE TITLE
Error while compiling RegCM4

### ISSUE THREAD

**Issue by mada0007** [ictp-esp/RegCM#3]
Dear all I have having this error after successfull submission

What am I doing wrong?

bin/sh ./config.status --recheck
running CONFIG_SHELL=/bin/sh /bin/sh ./configure CC=gcc FC=gfortran CFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe LDFLAGS=-Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs CPPFLAGS=-D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 --no-create --no-recursion
checking build system type... x86_64-apple-darwin18.7.0
checking host system type... x86_64-apple-darwin18.7.0
checking how to print strings... printf
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Users/mada0007/anaconda3/bin/x86_64-apple-darwin13.4.0-ld
checking if the linker (/Users/mada0007/anaconda3/bin/x86_64-apple-darwin13.4.0-ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /Users/mada0007/anaconda3/bin/x86_64-apple-darwin13.4.0-nm
checking the name lister (/Users/mada0007/anaconda3/bin/x86_64-apple-darwin13.4.0-nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin18.7.0 file names to x86_64-apple-darwin18.7.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin18.7.0 file names to toolchain format... func_convert_file_noop
checking for /Users/mada0007/anaconda3/bin/x86_64-apple-darwin13.4.0-ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... no
checking for strip... /Users/mada0007/anaconda3/bin/x86_64-apple-darwin13.4.0-strip
checking for ranlib... /Users/mada0007/anaconda3/bin/x86_64-apple-darwin13.4.0-ranlib
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking command to parse /Users/mada0007/anaconda3/bin/x86_64-apple-darwin13.4.0-nm output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... /Users/mada0007/anaconda3/bin/x86_64-apple-darwin13.4.0-nmedit
checking for lipo... /Users/mada0007/anaconda3/bin/x86_64-apple-darwin13.4.0-lipo
checking for otool... /Users/mada0007/anaconda3/bin/x86_64-apple-darwin13.4.0-otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Users/mada0007/anaconda3/bin/x86_64-apple-darwin13.4.0-ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.7.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking for ranlib... (cached) /Users/mada0007/anaconda3/bin/x86_64-apple-darwin13.4.0-ranlib
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking whether we are using the GNU Fortran compiler... yes
checking whether gfortran accepts -g... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gfortran option to produce PIC... -fno-common
checking if gfortran PIC flag -fno-common works... yes
checking if gfortran static flag -static works... no
checking if gfortran supports -c -o file.o... yes
checking if gfortran supports -c -o file.o... (cached) yes
checking whether the gfortran linker (/Users/mada0007/anaconda3/bin/x86_64-apple-darwin13.4.0-ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.7.0 dyld
checking how to hardcode library paths into programs... immediate
checking if nf-config program is present... no
checking if nc-config program is present... yes
checking whether byte ordering is bigendian... no
checking for Fortran name-mangling scheme... lower case, underscore, no extra underscore
configure: checking for NetCDF...
configure: checking for netcdf.h...
checking netcdf.h usability... yes
checking netcdf.h presence... yes
checking for netcdf.h... yes
configure: checking for libnetcdf.a...
checking for nc_close in -lnetcdf... yes
configure: checking for libnetcdff.a...
checking for nf_close in -lnetcdf... no
configure: checking for libnetcdff.a...
checking for nf_close in -lnetcdff... yes
configure: checking for NetCDF module file...
checking for mpifort... mpifort
checking for MPI_Init... no
checking for MPI_Init in -lfmpi... no
checking for MPI_Init in -lmpichf90... no
checking for MPI_Init in -lmpi... no
checking for MPI_Init in -lmpich... no
checking that generated files are newer than configure... done
configure: creating ./config.status
 /bin/sh ./config.status
config.status: creating Makefile
config.status: creating external/Makefile
config.status: creating Share/Makefile
config.status: creating PreProc/Makefile
config.status: creating PreProc/Terrain/Makefile
config.status: creating PreProc/ICBC/Makefile
config.status: creating PreProc/CH_EMISSIONS/Makefile
config.status: creating PreProc/CH_EMISSIONS/interpolation/Makefile
config.status: creating PreProc/CH_EMISSIONS/interpolation/tools/Makefile
config.status: creating PreProc/CH_EMISSIONS/interpolation/tools/REGCM_grid/Makefile
config.status: creating PreProc/CLM/Makefile
config.status: creating PreProc/CLM45/Makefile
config.status: creating PostProc/Makefile
config.status: creating Main/mpplib/Makefile
config.status: creating Main/netlib/Makefile
config.status: creating Main/Makefile
config.status: creating Main/batslib/Makefile
config.status: creating Main/clmlib/Makefile
config.status: creating Main/ocnlib/Makefile
config.status: creating Main/clmlib/clm4.5/Makefile
config.status: creating Main/chemlib/Makefile
config.status: creating Main/chemlib/GAS_CBMZ_NEW/Makefile
config.status: creating Main/cumlib/Makefile
config.status: creating Main/radlib/Makefile
config.status: creating Main/radlib/RRTMG_SW/Makefile
config.status: creating Main/pbllib/Makefile
config.status: creating Tools/Programs/CheckSun/Makefile
config.status: creating Tools/Programs/RegCM_read/Makefile
config.status: creating Tools/Programs/timeseries/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing libtool commands
config.status: executing depfiles commands
Making install in external
make[1]: Entering directory '/Users/mada0007/Documents/softwares/RegCM-4.5.0/external'
make[2]: Entering directory '/Users/mada0007/Documents/softwares/RegCM-4.5.0/external'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/Users/mada0007/Documents/softwares/RegCM-4.5.0/external'
make[1]: Leaving directory '/Users/mada0007/Documents/softwares/RegCM-4.5.0/external'
Making install in Share
make[1]: Entering directory '/Users/mada0007/Documents/softwares/RegCM-4.5.0/Share'
make[2]: Entering directory '/Users/mada0007/Documents/softwares/RegCM-4.5.0/Share'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/Users/mada0007/Documents/softwares/RegCM-4.5.0/Share'
make[1]: Leaving directory '/Users/mada0007/Documents/softwares/RegCM-4.5.0/Share'
Making install in PreProc
make[1]: Entering directory '/Users/mada0007/Documents/softwares/RegCM-4.5.0/PreProc'
Making install in Terrain
make[2]: Entering directory '/Users/mada0007/Documents/softwares/RegCM-4.5.0/PreProc/Terrain'
/bin/sh ../../libtool  --tag=FC   --mode=link gfortran  -O3 -mtune=native -march=native -fconvert=big-endian -fno-range-check -finline-functions -L/Users/mada0007/Documents/softwares/RegCM-4.5.0/external   -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -o terrain mod_header.o mod_block.o mod_fudge.o mod_maps.o mod_write.o mod_smooth.o mod_maputils.o mod_intldtr.o mod_rdldtr.o mod_moist.o terrain.o  -L/Users/mada0007/Documents/softwares/RegCM-4.5.0/Share -lrcmlib -lnetcdff  -L/usr/local/Cellar/netcdf/4.7.4/lib -lnetcdf
libtool: link: gfortran -O3 -mtune=native -march=native -fconvert=big-endian -fno-range-check -finline-functions -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -o terrain mod_header.o mod_block.o mod_fudge.o mod_maps.o mod_write.o mod_smooth.o mod_maputils.o mod_intldtr.o mod_rdldtr.o mod_moist.o terrain.o  -L/Users/mada0007/Documents/softwares/RegCM-4.5.0/external -L/Users/mada0007/Documents/softwares/RegCM-4.5.0/Share -lrcmlib -lnetcdff -L/usr/local/Cellar/netcdf/4.7.4/lib -lnetcdf
collect2: fatal error: ld terminated with signal 11 [Segmentation fault: 11]
compilation terminated.
ld: archive has no table of contents file '/Users/mada0007/Documents/softwares/RegCM-4.5.0/Share/librcmlib.a' for architecture x86_64
make[2]: *** [Makefile:400: terrain] Error 1
make[2]: Leaving directory '/Users/mada0007/Documents/softwares/RegCM-4.5.0/PreProc/Terrain'
make[1]: *** [Makefile:385: install-recursive] Error 1
make[1]: Leaving directory '/Users/mada0007/Documents/softwares/RegCM-4.5.0/PreProc'
make: *** [Makefile:431: install-recursive] Error 1

**Comment by graziano-giuliani** [comment]
This looks like a compiler bug or a system resources issue on the compiling OS. For the latter check user resources using limits or ulimit -a and try to increase the stack space or ask system administrator to do this for your user if the limit is a hard one. If the error persist, try upgrading the compiler. What is the exact OS/compiler you are using?

**Comment by mada0007** [comment]
Thanks I am using Mac OS X version 10.14.6

And a print of my gcc is as follows



(base) MU00152044X:RegCM-4.5.0 mada0007$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

** 
Mustapha Adamu
PhD candidate
ARC Centre of Excellence for Climate Extremes,
School of Earth, Atmosphere and Environment
Room 216, 
9 Rainforest Walk 
Monash University
Clayton, Victoria,
Australia, 3800

**  +61435887971

**Comment by mada0007** [comment]
I have tried to increase the stack space and update compiler to no avail
** 
Mustapha Adamu
PhD candidate
ARC Centre of Excellence for Climate Extremes,
School of Earth, Atmosphere and Environment
Room 216, 
9 Rainforest Walk 
Monash University
Clayton, Victoria,
Australia, 3800

**  +61435887971

**Comment by graziano-giuliani** [comment]
Closed a compiler bug.
