### ISSUE TITLE
"make" command error 

### ISSUE THREAD

**Issue by naushin2000** [ictp-esp/RegCM#9]
Hi, I have installed binutils and essentials, libtools before the configure step. However, it is showing "no" in some parts (MPI_Init) of the configure step. Is that an issue? Besides, I am facing problems while executing the "make" command. 
Please have a look. 
Thank you.

![WhatsApp Image 2021-07-06 at 5 16 45 PM](https://user-images.githubusercontent.com/86214260/124596209-a1b2e200-de7f-11eb-94da-0f1b657e577f.jpeg)
![WhatsApp Image 2021-07-06 at 5 17 03 PM](https://user-images.githubusercontent.com/86214260/124596214-a4153c00-de7f-11eb-877b-016b8c88bb3a.jpeg)

**Comment by graziano-giuliani** [comment]
The RegCM models require two external libraries: MPI and netCDF. On a Ubuntu Linux distribution, you can install libopenmpi-dev, openmpi-bin, libnetcdff-dev, netcdf-bin

**Comment by naushin2000** [comment]
Thank you so much for your response. All the above mentioned libraries are already installed. But, I am still facing the same issue. Any help, please?

**Comment by graziano-giuliani** [comment]
Do you have multiple mpi libraries?

update-alternatives --get-selections | grep mpi

**Comment by naushin2000** [comment]
Please have a look.  Thank you.
![WhatsApp Image 2021-07-06 at 10 26 49 PM](https://user-images.githubusercontent.com/86214260/124639139-6decb200-dea9-11eb-8192-0fcd68bb4ed9.jpeg)
